export const heroData = [
    {
        id: 1,
        name: "npc_dota_hero_antimage",
        localized_name: "Anti-Mage",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Nuker"],
        img: "./src/assets/antimage_full.png",
        icon: "/apps/dota2/images/heroes/antimage_icon.png",
        base_health: 225,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 200,
        base_attack_max: 200,
        base_str: 23,
        base_agi: 24,
        base_int: 12,
    },
    {
        id: 2,
        name: "npc_dota_hero_axe",
        localized_name: "Axe",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Durable", "Disabler", "Jungler"],
        img: "./src/assets/axe_full.png",
        icon: "/apps/dota2/images/heroes/axe_icon.png",
        base_health: 350,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 200,
        base_attack_max: 200,
        base_str: 25,
        base_agi: 20,
        base_int: 18,
    },
    {
        id: 3,
        name: "npc_dota_hero_bane",
        localized_name: "Bane",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker", "Durable"],
        img: "./src/assets/bane_full.png",
        icon: "/apps/dota2/images/heroes/bane_icon.png",
        base_health: 150,
        base_health_regen: 9,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 100,
        base_attack_max: 200,
        base_str: 23,
        base_agi: 23,
        base_int: 23,
    },
    {
        id: 4,
        name: "npc_dota_hero_bloodseeker",
        localized_name: "Bloodseeker",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Disabler", "Jungler", "Nuker", "Initiator"],
        img:
            "./src/assets/bloodseeker_full.png",
        icon: "/apps/dota2/images/heroes/bloodseeker_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 100,
        base_attack_max: 200,
        base_str: 24,
        base_agi: 24,
        base_int: 18,
    },
    {
        id: 5,
        name: "npc_dota_hero_crystal_maiden",
        localized_name: "Crystal Maiden",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker", "Jungler"],
        img:
            "./src/assets/crystal_maiden_full.png",
        icon: "/apps/dota2/images/heroes/crystal_maiden_icon.png",
        base_health: 120,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 30,
        base_attack_max: 36,
        base_str: 18,
        base_agi: 16,
        base_int: 14,
    },
    {
        id: 6,
        name: "npc_dota_hero_drow_ranger",
        localized_name: "Drow Ranger",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Disabler", "Pusher"],
        img:
            "./src/assets/drow_ranger_full.png",
        icon: "/apps/dota2/images/heroes/drow_ranger_icon.png",
        base_health: 180,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 19,
        base_attack_max: 30,
        base_str: 17,
        base_agi: 29,
        base_int: 15,
    },
    {
        id: 7,
        name: "npc_dota_hero_earthshaker",
        localized_name: "Earthshaker",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Initiator", "Disabler", "Nuker"],
        img:
            "./src/assets/earthshaker_full.png",
        icon: "/apps/dota2/images/heroes/earthshaker_icon.png",
        base_health: 250,
        base_health_regen: 1,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 27,
        base_attack_max: 37,
        base_str: 22,
        base_agi: 12,
        base_int: 16,
    },
    {
        id: 8,
        name: "npc_dota_hero_juggernaut",
        localized_name: "Juggernaut",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Pusher", "Escape"],
        img:
            "./src/assets/juggernaut_full.png",
        icon: "/apps/dota2/images/heroes/juggernaut_icon.png",
        base_health: 200,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 12,
        base_attack_max: 16,
        base_str: 21,
        base_agi: 36,
        base_int: 14,
    },
    {
        id: 9,
        name: "npc_dota_hero_mirana",
        localized_name: "Mirana",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Support", "Escape", "Nuker", "Disabler"],
        img: "./src/assets/mirana_full.png",
        icon: "/apps/dota2/images/heroes/mirana_icon.png",
        base_health: 175,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 25,
        base_attack_max: 30,
        base_str: 18,
        base_agi: 18,
        base_int: 19,
    },
    {
        id: 10,
        name: "npc_dota_hero_morphling",
        localized_name: "Morphling",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Escape", "Durable", "Nuker", "Disabler"],
        img: "./src/assets/morphling_full.png",
        icon: "/apps/dota2/images/heroes/morphling_icon.png",
        base_health: 300,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 9,
        base_attack_max: 18,
        base_str: 20,
        base_agi: 24,
        base_int: 13,
    },
    {
        id: 11,
        name: "npc_dota_hero_nevermore",
        localized_name: "Shadow Fiend",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Nuker"],
        img: "./src/assets/nevermore_full.png",
        icon: "/apps/dota2/images/heroes/nevermore_icon.png",
        base_health: 150,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0.3,
        base_armor: 20.5,
        base_attack_min: 15,
        base_attack_max: 21,
        base_str: 19,
        base_agi: 20,
        base_int: 18,
    },
    {
        id: 12,
        name: "npc_dota_hero_phantom_lancer",
        localized_name: "Phantom Lancer",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Pusher", "Nuker"],
        img:
            "./src/assets/phantom_lancer_full.png",
        icon: "/apps/dota2/images/heroes/phantom_lancer_icon.png",
        base_health: 280,
        base_health_regen: 15,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 22,
        base_attack_max: 44,
        base_str: 19,
        base_agi: 29,
        base_int: 19,
    },
    {
        id: 13,
        name: "npc_dota_hero_puck",
        localized_name: "Puck",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Initiator", "Disabler", "Escape", "Nuker"],
        img: "./src/assets/puck_full.png",
        icon: "/apps/dota2/images/heroes/puck_icon.png",
        base_health: 145,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 30,
        base_attack_max: 41,
        base_str: 17,
        base_agi: 22,
        base_int: 23,
    },
    {
        id: 14,
        name: "npc_dota_hero_pudge",
        localized_name: "Pudge",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Disabler", "Initiator", "Durable", "Nuker"],
        img: "./src/assets/pudge_full.png",
        icon: "/apps/dota2/images/heroes/pudge_icon.png",
        base_health: 400,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 40,
        base_attack_max: 46,
        base_str: 25,
        base_agi: 14,
        base_int: 16,
    },
    {
        id: 15,
        name: "npc_dota_hero_razor",
        localized_name: "Razor",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Durable", "Nuker", "Pusher"],
        img: "./src/assets/razor_full.png",
        icon: "/apps/dota2/images/heroes/razor_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 23,
        base_attack_max: 25,
        base_str: 22,
        base_agi: 22,
        base_int: 21,
    },
    {
        id: 16,
        name: "npc_dota_hero_sand_king",
        localized_name: "Sand King",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Support", "Nuker", "Escape", "Jungler"],
        img: "./src/assets/sand_king_full.png",
        icon: "/apps/dota2/images/heroes/sand_king_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 23,
        base_attack_max: 33,
        base_str: 22,
        base_agi: 19,
        base_int: 19,
    },
    {
        id: 17,
        name: "npc_dota_hero_storm_spirit",
        localized_name: "Storm Spirit",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Escape", "Nuker", "Initiator", "Disabler"],
        img:
            "./src/assets/storm_spirit_full.png",
        icon: "/apps/dota2/images/heroes/storm_spirit_icon.png",
        base_health: 170,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 26,
        base_attack_max: 36,
        base_str: 21,
        base_agi: 22,
        base_int: 23,
    },
    {
        id: 18,
        name: "npc_dota_hero_sven",
        localized_name: "Sven",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img: "./src/assets/sven_full.png",
        icon: "/apps/dota2/images/heroes/sven_icon.png",
        base_health: 270,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 43,
        base_attack_max: 45,
        base_str: 23,
        base_agi: 21,
        base_int: 16,
    },
    {
        id: 19,
        name: "npc_dota_hero_tiny",
        localized_name: "Tiny",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Nuker", "Pusher", "Initiator", "Durable", "Disabler"],
        img: "./src/assets/tiny_full.png",
        icon: "/apps/dota2/images/heroes/tiny_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 44,
        base_attack_max: 50,
        base_str: 30,
        base_agi: 0,
        base_int: 17,
    },
    {
        id: 20,
        name: "npc_dota_hero_vengefulspirit",
        localized_name: "Vengeful Spirit",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Support", "Initiator", "Disabler", "Nuker", "Escape"],
        img:
            "./src/assets/vengefulspirit_full.png",
        icon: "/apps/dota2/images/heroes/vengefulspirit_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 12,
        base_attack_max: 20,
        base_str: 19,
        base_agi: 27,
        base_int: 13,
    },
    {
        id: 21,
        name: "npc_dota_hero_windrunner",
        localized_name: "Windranger",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Support", "Disabler", "Escape", "Nuker"],
        img:
            "./src/assets/windrunner_full.png",
        icon: "/apps/dota2/images/heroes/windrunner_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 24,
        base_attack_max: 36,
        base_str: 18,
        base_agi: 17,
        base_int: 18,
    },
    {
        id: 22,
        name: "npc_dota_hero_zuus",
        localized_name: "Zeus",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Nuker"],
        img: "./src/assets/zuus_full.png",
        icon: "/apps/dota2/images/heroes/zuus_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0.25,
        base_armor: 20.5,
        base_attack_min: 33,
        base_attack_max: 41,
        base_str: 21,
        base_agi: 11,
        base_int: 21,
    },
    {
        id: 23,
        name: "npc_dota_hero_kunkka",
        localized_name: "Kunkka",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Support", "Disabler", "Initiator", "Durable", "Nuker"],
        img: "./src/assets/kunkka_full.png",
        icon: "/apps/dota2/images/heroes/kunkka_icon.png",
        base_health: 220,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 26,
        base_attack_max: 36,
        base_str: 24,
        base_agi: 14,
        base_int: 18,
    },
    {
        id: 25,
        name: "npc_dota_hero_lina",
        localized_name: "Lina",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Carry", "Nuker", "Disabler"],
        img: "./src/assets/lina_full.png",
        icon: "/apps/dota2/images/heroes/lina_icon.png",
        base_health: 225,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 21,
        base_attack_max: 33,
        base_str: 20,
        base_agi: 23,
        base_int: 30,
    },
    {
        id: 26,
        name: "npc_dota_hero_lion",
        localized_name: "Lion",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker", "Initiator"],
        img: "./src/assets/lion_full.png",
        icon: "/apps/dota2/images/heroes/lion_icon.png",
        base_health: 90,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 29,
        base_attack_max: 35,
        base_str: 18,
        base_agi: 15,
        base_int: 18,
    },
    {
        id: 27,
        name: "npc_dota_hero_shadow_shaman",
        localized_name: "Shadow Shaman",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Pusher", "Disabler", "Nuker", "Initiator"],
        img:
            "./src/assets/shadow_shaman_full.png",
        icon: "/apps/dota2/images/heroes/shadow_shaman_icon.png",
        base_health: 120,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 52,
        base_attack_max: 59,
        base_str: 23,
        base_agi: 16,
        base_int: 19,
    },
    {
        id: 28,
        name: "npc_dota_hero_slardar",
        localized_name: "Slardar",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Durable", "Initiator", "Disabler", "Escape"],
        img: "./src/assets/slardar_full.png",
        icon: "/apps/dota2/images/heroes/slardar_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 30,
        base_attack_max: 38,
        base_str: 21,
        base_agi: 17,
        base_int: 15,
    },
    {
        id: 29,
        name: "npc_dota_hero_tidehunter",
        localized_name: "Tidehunter",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Durable", "Disabler", "Nuker"],
        img:
            "./src/assets/tidehunter_full.png",
        icon: "/apps/dota2/images/heroes/tidehunter_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 25,
        base_attack_max: 31,
        base_str: 22,
        base_agi: 15,
        base_int: 16,
    },
    {
        id: 30,
        name: "npc_dota_hero_witch_doctor",
        localized_name: "Witch Doctor",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler"],
        img:
            "./src/assets/witch_doctor_full.png",
        icon: "/apps/dota2/images/heroes/witch_doctor_icon.png",
        base_health: 120,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 29,
        base_attack_max: 39,
        base_str: 18,
        base_agi: 13,
        base_int: 22,
    },
    {
        id: 31,
        name: "npc_dota_hero_lich",
        localized_name: "Lich",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker"],
        img: "./src/assets/lich_full.png",
        icon: "/apps/dota2/images/heroes/lich_icon.png",
        base_health: 140,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0.75,
        base_armor: 20,
        base_attack_min: 26,
        base_attack_max: 35,
        base_str: 20,
        base_agi: 15,
        base_int: 20,
    },
    {
        id: 32,
        name: "npc_dota_hero_riki",
        localized_name: "Riki",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Disabler"],
        img: "./src/assets/riki_full.png",
        icon: "/apps/dota2/images/heroes/riki_icon.png",
        base_health: 225,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 21,
        base_attack_max: 25,
        base_str: 18,
        base_agi: 30,
        base_int: 14,
    },
    {
        id: 33,
        name: "npc_dota_hero_enigma",
        localized_name: "Enigma",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Disabler", "Jungler", "Initiator", "Pusher"],
        img: "./src/assets/enigma_full.png",
        icon: "/apps/dota2/images/heroes/enigma_icon.png",
        base_health: 160,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 24,
        base_attack_max: 30,
        base_str: 21,
        base_agi: 14,
        base_int: 18,
    },
    {
        id: 34,
        name: "npc_dota_hero_tinker",
        localized_name: "Tinker",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Pusher"],
        img: "./src/assets/tinker_full.png",
        icon: "/apps/dota2/images/heroes/tinker_icon.png",
        base_health: 160,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0.25,
        base_armor: 27,
        base_attack_min: 24,
        base_attack_max: 30,
        base_str: 17,
        base_agi: 13,
        base_int: 28,
    },
    {
        id: 35,
        name: "npc_dota_hero_sniper",
        localized_name: "Sniper",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Nuker"],
        img: "./src/assets/sniper_full.png",
        icon: "/apps/dota2/images/heroes/sniper_icon.png",
        base_health: 125,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 25,
        base_attack_max: 50,
        base_str: 19,
        base_agi: 21,
        base_int: 15,
    },
    {
        id: 36,
        name: "npc_dota_hero_necrolyte",
        localized_name: "Necrophos",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Durable", "Disabler"],
        img: "./src/assets/necrolyte_full.png",
        icon: "/apps/dota2/images/heroes/necrolyte_icon.png",
        base_health: 280,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 26,
        base_attack_max: 30,
        base_str: 18,
        base_agi: 12,
        base_int: 20,
    },
    {
        id: 37,
        name: "npc_dota_hero_warlock",
        localized_name: "Warlock",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Initiator", "Disabler"],
        img: "./src/assets/warlock_full.png",
        icon: "/apps/dota2/images/heroes/warlock_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 24,
        base_attack_max: 34,
        base_str: 26,
        base_agi: 10,
        base_int: 25,
    },
    {
        id: 38,
        name: "npc_dota_hero_beastmaster",
        localized_name: "Beastmaster",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Durable", "Nuker"],
        img:
            "./src/assets/beastmaster_full.png",
        icon: "/apps/dota2/images/heroes/beastmaster_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 41,
        base_attack_max: 45,
        base_str: 23,
        base_agi: 18,
        base_int: 16,
    },
    {
        id: 39,
        name: "npc_dota_hero_queenofpain",
        localized_name: "Queen of Pain",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Escape"],
        img:
            "./src/assets/queenofpain_full.png",
        icon: "/apps/dota2/images/heroes/queenofpain_icon.png",
        base_health: 140,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 20,
        base_attack_max: 28,
        base_str: 18,
        base_agi: 22,
        base_int: 25,
    },
    {
        id: 40,
        name: "npc_dota_hero_venomancer",
        localized_name: "Venomancer",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Support", "Nuker", "Initiator", "Pusher", "Disabler"],
        img:
            "./src/assets/venomancer_full.png",
        icon: "/apps/dota2/images/heroes/venomancer_icon.png",
        base_health: 190,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 16,
        base_attack_max: 18,
        base_str: 19,
        base_agi: 26,
        base_int: 19,
    },
    {
        id: 41,
        name: "npc_dota_hero_faceless_void",
        localized_name: "Faceless Void",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Initiator", "Disabler", "Escape", "Durable"],
        img:
            "./src/assets/faceless_void_full.png",
        icon: "/apps/dota2/images/heroes/faceless_void_icon.png",
        base_health: 200,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 33,
        base_attack_max: 39,
        base_str: 24,
        base_agi: 23,
        base_int: 15,
    },
    {
        id: 42,
        name: "npc_dota_hero_skeleton_king",
        localized_name: "Wraith King",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Support", "Durable", "Disabler", "Initiator"],
        img:
            "./src/assets/skeleton_king_full.png",
        icon: "/apps/dota2/images/heroes/skeleton_king_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 39,
        base_attack_max: 41,
        base_str: 22,
        base_agi: 18,
        base_int: 18,
    },
    {
        id: 43,
        name: "npc_dota_hero_death_prophet",
        localized_name: "Death Prophet",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Pusher", "Nuker", "Disabler"],
        img:
            "./src/assets/death_prophet_full.png",
        icon: "/apps/dota2/images/heroes/death_prophet_icon.png",
        base_health: 120,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 29,
        base_attack_max: 41,
        base_str: 19,
        base_agi: 14,
        base_int: 21,
    },
    {
        id: 44,
        name: "npc_dota_hero_phantom_assassin",
        localized_name: "Phantom Assassin",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape"],
        img:
            "./src/assets/phantom_assassin_full.png",
        icon: "/apps/dota2/images/heroes/phantom_assassin_icon.png",
        base_health: 150,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 23,
        base_attack_max: 25,
        base_str: 21,
        base_agi: 23,
        base_int: 15,
    },
    {
        id: 45,
        name: "npc_dota_hero_pugna",
        localized_name: "Pugna",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Nuker", "Pusher"],
        img: "./src/assets/pugna_full.png",
        icon: "/apps/dota2/images/heroes/pugna_icon.png",
        base_health: 120,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0.5,
        base_armor: 20.5,
        base_attack_min: 19,
        base_attack_max: 27,
        base_str: 19,
        base_agi: 16,
        base_int: 24,
    },
    {
        id: 46,
        name: "npc_dota_hero_templar_assassin",
        localized_name: "Templar Assassin",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Escape"],
        img:
            "./src/assets/templar_assassin_full.png",
        icon: "/apps/dota2/images/heroes/templar_assassin_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 30,
        base_attack_max: 36,
        base_str: 19,
        base_agi: 23,
        base_int: 20,
    },
    {
        id: 47,
        name: "npc_dota_hero_viper",
        localized_name: "Viper",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Durable", "Initiator", "Disabler"],
        img: "./src/assets/viper_full.png",
        icon: "/apps/dota2/images/heroes/viper_icon.png",
        base_health: 165,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 23,
        base_attack_max: 25,
        base_str: 21,
        base_agi: 21,
        base_int: 15,
    },
    {
        id: 48,
        name: "npc_dota_hero_luna",
        localized_name: "Luna",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Pusher"],
        img: "./src/assets/luna_full.png",
        icon: "/apps/dota2/images/heroes/luna_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 24,
        base_attack_max: 30,
        base_str: 16,
        base_agi: 18,
        base_int: 16,
    },
    {
        id: 49,
        name: "npc_dota_hero_dragon_knight",
        localized_name: "Dragon Knight",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Pusher", "Durable", "Disabler", "Initiator", "Nuker"],
        img:
            "./src/assets/dragon_knight_full.png",
        icon: "/apps/dota2/images/heroes/dragon_knight_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 31,
        base_attack_max: 37,
        base_str: 19,
        base_agi: 19,
        base_int: 15,
    },
    {
        id: 50,
        name: "npc_dota_hero_dazzle",
        localized_name: "Dazzle",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler"],
        img: "./src/assets/dazzle_full.png",
        icon: "/apps/dota2/images/heroes/dazzle_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 22,
        base_attack_max: 28,
        base_str: 18,
        base_agi: 21,
        base_int: 25,
    },
    {
        id: 51,
        name: "npc_dota_hero_rattletrap",
        localized_name: "Clockwerk",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Durable", "Nuker"],
        img:
            "./src/assets/rattletrap_full.png",
        icon: "/apps/dota2/images/heroes/rattletrap_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 24,
        base_attack_max: 26,
        base_str: 26,
        base_agi: 13,
        base_int: 17,
    },
    {
        id: 52,
        name: "npc_dota_hero_leshrac",
        localized_name: "Leshrac",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Support", "Nuker", "Pusher", "Disabler"],
        img: "./src/assets/leshrac_full.png",
        icon: "/apps/dota2/images/heroes/leshrac_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 19,
        base_attack_max: 23,
        base_str: 18,
        base_agi: 23,
        base_int: 22,
    },
    {
        id: 53,
        name: "npc_dota_hero_furion",
        localized_name: "Nature's Prophet",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Jungler", "Pusher", "Escape", "Nuker"],
        img: "./src/assets/furion_full.png",
        icon: "/apps/dota2/images/heroes/furion_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 27,
        base_attack_max: 41,
        base_str: 21,
        base_agi: 18,
        base_int: 23,
    },
    {
        id: 54,
        name: "npc_dota_hero_life_stealer",
        localized_name: "Lifestealer",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Durable", "Jungler", "Escape", "Disabler"],
        img:
            "./src/assets/life_stealer_full.png",
        icon: "/apps/dota2/images/heroes/life_stealer_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 27,
        base_attack_max: 37,
        base_str: 25,
        base_agi: 18,
        base_int: 15,
    },
    {
        id: 55,
        name: "npc_dota_hero_dark_seer",
        localized_name: "Dark Seer",
        primary_attr: "int",
        attack_type: "melee",
        roles: ["Initiator", "Jungler", "Escape", "Disabler"],
        img: "./src/assets/dark_seer_full.png",
        icon: "/apps/dota2/images/heroes/dark_seer_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 33,
        base_attack_max: 39,
        base_str: 21,
        base_agi: 12,
        base_int: 21,
    },
    {
        id: 56,
        name: "npc_dota_hero_clinkz",
        localized_name: "Clinkz",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Escape", "Pusher"],
        img: "./src/assets/clinkz_full.png",
        icon: "/apps/dota2/images/heroes/clinkz_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0.25,
        base_armor: 20.5,
        base_attack_min: 15,
        base_attack_max: 21,
        base_str: 12,
        base_agi: 22,
        base_int: 18,
    },
    {
        id: 57,
        name: "npc_dota_hero_omniknight",
        localized_name: "Omniknight",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Durable", "Nuker"],
        img:
            "./src/assets/omniknight_full.png",
        icon: "/apps/dota2/images/heroes/omniknight_icon.png",
        base_health: 400,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 31,
        base_attack_max: 41,
        base_str: 22,
        base_agi: 15,
        base_int: 15,
    },
    {
        id: 58,
        name: "npc_dota_hero_enchantress",
        localized_name: "Enchantress",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Jungler", "Pusher", "Durable", "Disabler"],
        img:
            "./src/assets/enchantress_full.png",
        icon: "/apps/dota2/images/heroes/enchantress_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 30,
        base_attack_max: 40,
        base_str: 17,
        base_agi: 19,
        base_int: 19,
    },
    {
        id: 59,
        name: "npc_dota_hero_huskar",
        localized_name: "Huskar",
        primary_attr: "str",
        attack_type: "range",
        roles: ["Carry", "Durable", "Initiator"],
        img: "./src/assets/huskar_full.png",
        icon: "/apps/dota2/images/heroes/huskar_icon.png",
        base_health: 320,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 19,
        base_attack_max: 24,
        base_str: 21,
        base_agi: 15,
        base_int: 18,
    },
    {
        id: 60,
        name: "npc_dota_hero_night_stalker",
        localized_name: "Night Stalker",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
        img:
            "./src/assets/night_stalker_full.png",
        icon: "/apps/dota2/images/heroes/night_stalker_icon.png",
        base_health: 250,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 38,
        base_attack_max: 42,
        base_str: 23,
        base_agi: 18,
        base_int: 13,
    },
    {
        id: 61,
        name: "npc_dota_hero_broodmother",
        localized_name: "Broodmother",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Pusher", "Escape", "Nuker"],
        img:
            "./src/assets/broodmother_full.png",
        icon: "/apps/dota2/images/heroes/broodmother_icon.png",
        base_health: 300,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 29,
        base_attack_max: 35,
        base_str: 18,
        base_agi: 15,
        base_int: 18,
    },
    {
        id: 62,
        name: "npc_dota_hero_bounty_hunter",
        localized_name: "Bounty Hunter",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Escape", "Nuker"],
        img:
            "./src/assets/bounty_hunter_full.png",
        icon: "/apps/dota2/images/heroes/bounty_hunter_icon.png",
        base_health: 100,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 24,
        base_attack_max: 38,
        base_str: 20,
        base_agi: 21,
        base_int: 19,
    },
    {
        id: 63,
        name: "npc_dota_hero_weaver",
        localized_name: "Weaver",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Escape"],
        img: "./src/assets/weaver_full.png",
        icon: "/apps/dota2/images/heroes/weaver_icon.png",
        base_health: 150,
        base_health_regen: 1,
        base_mana: 75,
        base_mana_regen: 0.4,
        base_armor: 20,
        base_attack_min: 36,
        base_attack_max: 46,
        base_str: 16,
        base_agi: 14,
        base_int: 13,
    },
    {
        id: 64,
        name: "npc_dota_hero_jakiro",
        localized_name: "Jakiro",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Pusher", "Disabler"],
        img: "./src/assets/jakiro_full.png",
        icon: "/apps/dota2/images/heroes/jakiro_icon.png",
        base_health: 220,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 35,
        base_str: 27,
        base_agi: 10,
        base_int: 26,
    },
    {
        id: 65,
        name: "npc_dota_hero_batrider",
        localized_name: "Batrider",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Initiator", "Jungler", "Disabler", "Escape"],
        img: "./src/assets/batrider_full.png",
        icon: "/apps/dota2/images/heroes/batrider_icon.png",
        base_health: 280,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 16,
        base_attack_max: 20,
        base_str: 28,
        base_agi: 15,
        base_int: 22,
    },
    {
        id: 66,
        name: "npc_dota_hero_chen",
        localized_name: "Chen",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Jungler", "Pusher"],
        img: "./src/assets/chen_full.png",
        icon: "/apps/dota2/images/heroes/chen_icon.png",
        base_health: 125,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 29,
        base_attack_max: 39,
        base_str: 25,
        base_agi: 15,
        base_int: 19,
    },
    {
        id: 67,
        name: "npc_dota_hero_spectre",
        localized_name: "Spectre",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Durable", "Escape"],
        img: "./src/assets/spectre_full.png",
        icon: "/apps/dota2/images/heroes/spectre_icon.png",
        base_health: 170,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 23,
        base_attack_max: 27,
        base_str: 23,
        base_agi: 23,
        base_int: 16,
    },
    {
        id: 68,
        name: "npc_dota_hero_ancient_apparition",
        localized_name: "Ancient Apparition",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker"],
        img:
            "./src/assets/ancient_apparition_full.png",
        icon: "/apps/dota2/images/heroes/ancient_apparition_icon.png",
        base_health: 125,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 21,
        base_attack_max: 31,
        base_str: 20,
        base_agi: 20,
        base_int: 23,
    },
    {
        id: 69,
        name: "npc_dota_hero_doom_bringer",
        localized_name: "Doom",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img:
            "./src/assets/doom_bringer_full.png",
        icon: "/apps/dota2/images/heroes/doom_bringer_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 43,
        base_str: 26,
        base_agi: 11,
        base_int: 15,
    },
    {
        id: 70,
        name: "npc_dota_hero_ursa",
        localized_name: "Ursa",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Jungler", "Durable", "Disabler"],
        img: "./src/assets/ursa_full.png",
        icon: "/apps/dota2/images/heroes/ursa_icon.png",
        base_health: 250,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 24,
        base_attack_max: 28,
        base_str: 24,
        base_agi: 18,
        base_int: 16,
    },
    {
        id: 71,
        name: "npc_dota_hero_spirit_breaker",
        localized_name: "Spirit Breaker",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Initiator", "Disabler", "Durable", "Escape"],
        img:
            "./src/assets/spirit_breaker_full.png",
        icon: "/apps/dota2/images/heroes/spirit_breaker_icon.png",
        base_health: 200,
        base_health_regen: 1.25,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 31,
        base_attack_max: 41,
        base_str: 29,
        base_agi: 17,
        base_int: 14,
    },
    {
        id: 72,
        name: "npc_dota_hero_gyrocopter",
        localized_name: "Gyrocopter",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Disabler"],
        img:
            "./src/assets/gyrocopter_full.png",
        icon: "/apps/dota2/images/heroes/gyrocopter_icon.png",
        base_health: 220,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 21,
        base_attack_max: 31,
        base_str: 22,
        base_agi: 19,
        base_int: 19,
    },
    {
        id: 73,
        name: "npc_dota_hero_alchemist",
        localized_name: "Alchemist",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Support", "Durable", "Disabler", "Initiator", "Nuker"],
        img: "./src/assets/alchemist_full.png",
        icon: "/apps/dota2/images/heroes/alchemist_icon.png",
        base_health: 400,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 24,
        base_attack_max: 33,
        base_str: 25,
        base_agi: 22,
        base_int: 25,
    },
    {
        id: 74,
        name: "npc_dota_hero_invoker",
        localized_name: "Invoker",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Disabler", "Escape", "Pusher"],
        img: "./src/assets/invoker_full.png",
        icon: "/apps/dota2/images/heroes/invoker_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 33,
        base_str: 18,
        base_agi: 14,
        base_int: 14,
    },
    {
        id: 75,
        name: "npc_dota_hero_silencer",
        localized_name: "Silencer",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Support", "Disabler", "Initiator", "Nuker"],
        img: "./src/assets/silencer_full.png",
        icon: "/apps/dota2/images/heroes/silencer_icon.png",
        base_health: 135,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 18,
        base_attack_max: 32,
        base_str: 19,
        base_agi: 22,
        base_int: 25,
    },
    {
        id: 76,
        name: "npc_dota_hero_obsidian_destroyer",
        localized_name: "Outworld Devourer",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Carry", "Nuker", "Disabler"],
        img:
            "./src/assets/obsidian_destroyer_full.png",
        icon: "/apps/dota2/images/heroes/obsidian_destroyer_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 16,
        base_attack_max: 31,
        base_str: 19,
        base_agi: 24,
        base_int: 28,
    },
    {
        id: 77,
        name: "npc_dota_hero_lycan",
        localized_name: "Lycan",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Pusher", "Jungler", "Durable", "Escape"],
        img: "./src/assets/lycan_full.png",
        icon: "/apps/dota2/images/heroes/lycan_icon.png",
        base_health: 280,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 30,
        base_attack_max: 35,
        base_str: 25,
        base_agi: 16,
        base_int: 17,
    },
    {
        id: 78,
        name: "npc_dota_hero_brewmaster",
        localized_name: "Brewmaster",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
        img:
            "./src/assets/brewmaster_full.png",
        icon: "/apps/dota2/images/heroes/brewmaster_icon.png",
        base_health: 200,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 29,
        base_attack_max: 36,
        base_str: 23,
        base_agi: 22,
        base_int: 14,
    },
    {
        id: 79,
        name: "npc_dota_hero_shadow_demon",
        localized_name: "Shadow Demon",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Initiator", "Nuker"],
        img:
            "./src/assets/shadow_demon_full.png",
        icon: "/apps/dota2/images/heroes/shadow_demon_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 29,
        base_attack_max: 33,
        base_str: 23,
        base_agi: 18,
        base_int: 21,
    },
    {
        id: 80,
        name: "npc_dota_hero_lone_druid",
        localized_name: "Lone Druid",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Pusher", "Jungler", "Durable"],
        img:
            "./src/assets/lone_druid_full.png",
        icon: "/apps/dota2/images/heroes/lone_druid_icon.png",
        base_health: 250,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 18,
        base_attack_max: 22,
        base_str: 18,
        base_agi: 20,
        base_int: 13,
    },
    {
        id: 81,
        name: "npc_dota_hero_chaos_knight",
        localized_name: "Chaos Knight",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Disabler", "Durable", "Pusher", "Initiator"],
        img:
            "./src/assets/chaos_knight_full.png",
        icon: "/apps/dota2/images/heroes/chaos_knight_icon.png",
        base_health: 280,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 29,
        base_attack_max: 59,
        base_str: 22,
        base_agi: 14,
        base_int: 18,
    },
    {
        id: 82,
        name: "npc_dota_hero_meepo",
        localized_name: "Meepo",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator", "Pusher"],
        img: "./src/assets/meepo_full.png",
        icon: "/apps/dota2/images/heroes/meepo_icon.png",
        base_health: 320,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 22,
        base_attack_max: 28,
        base_str: 24,
        base_agi: 24,
        base_int: 20,
    },
    {
        id: 83,
        name: "npc_dota_hero_treant",
        localized_name: "Treant Protector",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Initiator", "Durable", "Disabler", "Escape"],
        img: "./src/assets/treant_full.png",
        icon: "/apps/dota2/images/heroes/treant_icon.png",
        base_health: 400,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0.5,
        base_armor: 27,
        base_attack_min: 62,
        base_attack_max: 70,
        base_str: 25,
        base_agi: 15,
        base_int: 20,
    },
    {
        id: 84,
        name: "npc_dota_hero_ogre_magi",
        localized_name: "Ogre Magi",
        primary_attr: "int",
        attack_type: "melee",
        roles: ["Support", "Nuker", "Disabler", "Durable", "Initiator"],
        img: "./src/assets/ogre_magi_full.png",
        icon: "/apps/dota2/images/heroes/ogre_magi_icon.png",
        base_health: 150,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 6,
        base_attack_min: 43,
        base_attack_max: 49,
        base_str: 25,
        base_agi: 14,
        base_int: 15,
    },
    {
        id: 85,
        name: "npc_dota_hero_undying",
        localized_name: "Undying",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Durable", "Disabler", "Nuker"],
        img: "./src/assets/undying_full.png",
        icon: "/apps/dota2/images/heroes/undying_icon.png",
        base_health: 400,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 35,
        base_attack_max: 43,
        base_str: 22,
        base_agi: 10,
        base_int: 27,
    },
    {
        id: 86,
        name: "npc_dota_hero_rubick",
        localized_name: "Rubick",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker"],
        img: "./src/assets/rubick_full.png",
        icon: "/apps/dota2/images/heroes/rubick_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 22,
        base_attack_max: 32,
        base_str: 21,
        base_agi: 19,
        base_int: 25,
    },
    {
        id: 87,
        name: "npc_dota_hero_disruptor",
        localized_name: "Disruptor",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker", "Initiator"],
        img: "./src/assets/disruptor_full.png",
        icon: "/apps/dota2/images/heroes/disruptor_icon.png",
        base_health: 220,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 29,
        base_attack_max: 33,
        base_str: 21,
        base_agi: 15,
        base_int: 20,
    },
    {
        id: 88,
        name: "npc_dota_hero_nyx_assassin",
        localized_name: "Nyx Assassin",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Disabler", "Nuker", "Initiator", "Escape"],
        img:
            "./src/assets/nyx_assassin_full.png",
        icon: "/apps/dota2/images/heroes/nyx_assassin_icon.png",
        base_health: 125,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 31,
        base_str: 18,
        base_agi: 19,
        base_int: 18,
    },
    {
        id: 89,
        name: "npc_dota_hero_naga_siren",
        localized_name: "Naga Siren",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Support", "Pusher", "Disabler", "Initiator", "Escape"],
        img:
            "./src/assets/naga_siren_full.png",
        icon: "/apps/dota2/images/heroes/naga_siren_icon.png",
        base_health: 300,
        base_health_regen: 15,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 23,
        base_attack_max: 25,
        base_str: 22,
        base_agi: 21,
        base_int: 21,
    },
    {
        id: 90,
        name: "npc_dota_hero_keeper_of_the_light",
        localized_name: "Keeper of the Light",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler", "Jungler"],
        img:
            "./src/assets/keeper_of_the_light_full.png",
        icon: "/apps/dota2/images/heroes/keeper_of_the_light_icon.png",
        base_health: 110,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 20,
        base_attack_max: 27,
        base_str: 16,
        base_agi: 15,
        base_int: 23,
    },
    {
        id: 91,
        name: "npc_dota_hero_wisp",
        localized_name: "Io",
        primary_attr: "str",
        attack_type: "range",
        roles: ["Support", "Escape", "Nuker"],
        img: "./src/assets/wisp_full.png",
        icon: "/apps/dota2/images/heroes/wisp_icon.png",
        base_health: 150,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 22,
        base_attack_max: 31,
        base_str: 17,
        base_agi: 14,
        base_int: 23,
    },
    {
        id: 92,
        name: "npc_dota_hero_visage",
        localized_name: "Visage",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Durable", "Disabler", "Pusher"],
        img: "./src/assets/visage_full.png",
        icon: "/apps/dota2/images/heroes/visage_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 23,
        base_attack_max: 33,
        base_str: 22,
        base_agi: 11,
        base_int: 22,
    },
    {
        id: 93,
        name: "npc_dota_hero_slark",
        localized_name: "Slark",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Disabler", "Nuker"],
        img: "./src/assets/slark_full.png",
        icon: "/apps/dota2/images/heroes/slark_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 33,
        base_attack_max: 41,
        base_str: 21,
        base_agi: 21,
        base_int: 16,
    },
    {
        id: 94,
        name: "npc_dota_hero_medusa",
        localized_name: "Medusa",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Disabler", "Durable"],
        img: "./src/assets/medusa_full.png",
        icon: "/apps/dota2/images/heroes/medusa_icon.png",
        base_health: 280,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 24,
        base_attack_max: 30,
        base_str: 15,
        base_agi: 22,
        base_int: 19,
    },
    {
        id: 95,
        name: "npc_dota_hero_troll_warlord",
        localized_name: "Troll Warlord",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Pusher", "Disabler", "Durable"],
        img:
            "./src/assets/troll_warlord_full.png",
        icon: "/apps/dota2/images/heroes/troll_warlord_icon.png",
        base_health: 150,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 23,
        base_attack_max: 35,
        base_str: 21,
        base_agi: 21,
        base_int: 13,
    },
    {
        id: 96,
        name: "npc_dota_hero_centaur",
        localized_name: "Centaur Warrunner",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Durable", "Initiator", "Disabler", "Nuker", "Escape"],
        img: "./src/assets/centaur_full.png",
        icon: "/apps/dota2/images/heroes/centaur_icon.png",
        base_health: 250,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 36,
        base_attack_max: 38,
        base_str: 27,
        base_agi: 15,
        base_int: 15,
    },
    {
        id: 97,
        name: "npc_dota_hero_magnataur",
        localized_name: "Magnus",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Nuker", "Escape"],
        img: "./src/assets/magnataur_full.png",
        icon: "/apps/dota2/images/heroes/magnataur_icon.png",
        base_health: 400,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 32,
        base_attack_max: 44,
        base_str: 25,
        base_agi: 15,
        base_int: 19,
    },
    {
        id: 98,
        name: "npc_dota_hero_shredder",
        localized_name: "Timbersaw",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Nuker", "Durable", "Escape"],
        img: "./src/assets/shredder_full.png",
        icon: "/apps/dota2/images/heroes/shredder_icon.png",
        base_health: 180,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 26,
        base_attack_max: 30,
        base_str: 21,
        base_agi: 16,
        base_int: 23,
    },
    {
        id: 99,
        name: "npc_dota_hero_bristleback",
        localized_name: "Bristleback",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Durable", "Initiator", "Nuker"],
        img:
            "./src/assets/bristleback_full.png",
        icon: "/apps/dota2/images/heroes/bristleback_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 22,
        base_attack_max: 32,
        base_str: 22,
        base_agi: 17,
        base_int: 14,
    },
    {
        id: 100,
        name: "npc_dota_hero_tusk",
        localized_name: "Tusk",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Nuker"],
        img: "./src/assets/tusk_full.png",
        icon: "/apps/dota2/images/heroes/tusk_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 31,
        base_str: 23,
        base_agi: 23,
        base_int: 18,
    },
    {
        id: 101,
        name: "npc_dota_hero_skywrath_mage",
        localized_name: "Skywrath Mage",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler"],
        img:
            "./src/assets/skywrath_mage_full.png",
        icon: "/apps/dota2/images/heroes/skywrath_mage_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 14,
        base_attack_max: 24,
        base_str: 21,
        base_agi: 13,
        base_int: 25,
    },
    {
        id: 102,
        name: "npc_dota_hero_abaddon",
        localized_name: "Abaddon",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Carry", "Durable"],
        img: "./src/assets/abaddon_full.png",
        icon: "/apps/dota2/images/heroes/abaddon_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 32,
        base_attack_max: 42,
        base_str: 23,
        base_agi: 23,
        base_int: 21,
    },
    {
        id: 103,
        name: "npc_dota_hero_elder_titan",
        localized_name: "Elder Titan",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Initiator", "Disabler", "Nuker", "Durable"],
        img:
            "./src/assets/elder_titan_full.png",
        icon: "/apps/dota2/images/heroes/elder_titan_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 23,
        base_attack_max: 33,
        base_str: 24,
        base_agi: 14,
        base_int: 23,
    },
    {
        id: 104,
        name: "npc_dota_hero_legion_commander",
        localized_name: "Legion Commander",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img:
            "./src/assets/legion_commander_full.png",
        icon: "/apps/dota2/images/heroes/legion_commander_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 35,
        base_attack_max: 39,
        base_str: 26,
        base_agi: 18,
        base_int: 20,
    },
    {
        id: 105,
        name: "npc_dota_hero_techies",
        localized_name: "Techies",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Nuker", "Disabler"],
        img: "./src/assets/techies_full.png",
        icon: "/apps/dota2/images/heroes/techies_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 1,
        base_armor: 50,
        base_attack_min: 9,
        base_attack_max: 11,
        base_str: 19,
        base_agi: 14,
        base_int: 22,
    },
    {
        id: 106,
        name: "npc_dota_hero_ember_spirit",
        localized_name: "Ember Spirit",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator"],
        img:
            "./src/assets/ember_spirit_full.png",
        icon: "/apps/dota2/images/heroes/ember_spirit_icon.png",
        base_health: 200,
        base_health_regen: 7,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 33,
        base_attack_max: 37,
        base_str: 21,
        base_agi: 22,
        base_int: 20,
    },
    {
        id: 107,
        name: "npc_dota_hero_earth_spirit",
        localized_name: "Earth Spirit",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Nuker", "Escape", "Disabler", "Initiator", "Durable"],
        img:
            "./src/assets/earth_spirit_full.png",
        icon: "/apps/dota2/images/heroes/earth_spirit_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 25,
        base_attack_max: 35,
        base_str: 21,
        base_agi: 17,
        base_int: 18,
    },
    {
        id: 108,
        name: "npc_dota_hero_abyssal_underlord",
        localized_name: "Underlord",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Support", "Nuker", "Disabler", "Durable", "Escape"],
        img:
            "./src/assets/abyssal_underlord_full.png",
        icon: "/apps/dota2/images/heroes/abyssal_underlord_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 37,
        base_attack_max: 43,
        base_str: 25,
        base_agi: 12,
        base_int: 17,
    },
    {
        id: 109,
        name: "npc_dota_hero_terrorblade",
        localized_name: "Terrorblade",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Pusher", "Nuker"],
        img:
            "./src/assets/terrorblade_full.png",
        icon: "/apps/dota2/images/heroes/terrorblade_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 7,
        base_attack_min: 26,
        base_attack_max: 32,
        base_str: 15,
        base_agi: 22,
        base_int: 19,
    },
    {
        id: 110,
        name: "npc_dota_hero_phoenix",
        localized_name: "Phoenix",
        primary_attr: "str",
        attack_type: "range",
        roles: ["Support", "Nuker", "Initiator", "Escape", "Disabler"],
        img: "./src/assets/phoenix_full.png",
        icon: "/apps/dota2/images/heroes/phoenix_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 26,
        base_attack_max: 36,
        base_str: 21,
        base_agi: 12,
        base_int: 18,
    },
    {
        id: 111,
        name: "npc_dota_hero_oracle",
        localized_name: "Oracle",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img: "./src/assets/oracle_full.png",
        icon: "/apps/dota2/images/heroes/oracle_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 18,
        base_attack_max: 24,
        base_str: 20,
        base_agi: 15,
        base_int: 21,
    },
    {
        id: 112,
        name: "npc_dota_hero_winter_wyvern",
        localized_name: "Winter Wyvern",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Disabler", "Nuker"],
        img:
            "./src/assets/winter_wyvern_full.png",
        icon: "/apps/dota2/images/heroes/winter_wyvern_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 12,
        base_attack_max: 19,
        base_str: 26,
        base_agi: 16,
        base_int: 26,
    },
    {
        id: 113,
        name: "npc_dota_hero_arc_warden",
        localized_name: "Arc Warden",
        primary_attr: "agi",
        attack_type: "range",
        roles: ["Carry", "Escape", "Nuker"],
        img:
            "./src/assets/arc_warden_full.png",
        icon: "/apps/dota2/images/heroes/arc_warden_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 27,
        base_attack_min: 31,
        base_attack_max: 41,
        base_str: 25,
        base_agi: 15,
        base_int: 24,
    },
    {
        id: 114,
        name: "npc_dota_hero_monkey_king",
        localized_name: "Monkey King",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Escape", "Disabler", "Initiator"],
        img:
            "./src/assets/monkey_king_full.png",
        icon: "/apps/dota2/images/heroes/monkey_king_icon.png",
        base_health: 200,
        base_health_regen: 15,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 30,
        base_attack_min: 29,
        base_attack_max: 35,
        base_str: 19,
        base_agi: 22,
        base_int: 20,
    },
    {
        id: 119,
        name: "npc_dota_hero_dark_willow",
        localized_name: "Dark Willow",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img:
            "./src/assets/dark_willow_full.png",
        icon: "/apps/dota2/images/heroes/dark_willow_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 27,
        base_attack_max: 35,
        base_str: 20,
        base_agi: 18,
        base_int: 18,
    },
    {
        id: 120,
        name: "npc_dota_hero_pangolier",
        localized_name: "Pangolier",
        primary_attr: "agi",
        attack_type: "melee",
        roles: ["Carry", "Nuker", "Disabler", "Durable", "Escape", "Initiator"],
        img: "./src/assets/pangolier_full.png",
        icon: "/apps/dota2/images/heroes/pangolier_icon.png",
        base_health: 200,
        base_health_regen: 10,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 33,
        base_attack_max: 39,
        base_str: 17,
        base_agi: 18,
        base_int: 16,
    },
    {
        id: 121,
        name: "npc_dota_hero_grimstroke",
        localized_name: "Grimstroke",
        primary_attr: "int",
        attack_type: "range",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img:
            "./src/assets/grimstroke_full.png",
        icon: "/apps/dota2/images/heroes/grimstroke_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20.5,
        base_attack_min: 27,
        base_attack_max: 31,
        base_str: 21,
        base_agi: 18,
        base_int: 23,
    },
    {
        id: 129,
        name: "npc_dota_hero_mars",
        localized_name: "Mars",
        primary_attr: "str",
        attack_type: "melee",
        roles: ["Carry", "Initiator", "Disabler", "Durable"],
        img: "./src/assets/mars_full.png",
        icon: "/apps/dota2/images/heroes/mars_icon.png",
        base_health: 200,
        base_health_regen: 5.5,
        base_mana: 75,
        base_mana_regen: 0,
        base_armor: 20,
        base_attack_min: 31,
        base_attack_max: 39,
        base_str: 23,
        base_agi: 20,
        base_int: 17,
    },
];

export default heroData